### ISSUE TITLE
JSON schema support (no doc generation)

### ISSUE THREAD

**Issue by Adovenmuehle** [heroku/plexy#2]

**Comment by dmathieu** [comment]
How about OpenAPI?

**Comment by mathias** [comment]
Possibly https://github.com/jonasschmidt/ex_json_schema.

I think we're deferring on JSON Schema support for right now.

**Comment by mathias** [comment]
@dmathieu https://github.com/interagent/pliny and the other interagent tooling is still built on JSON Schema, so for compatibility/integration, we wanted to stick with what is used there.

**Comment by dmathieu** [comment]
@mathias OpenAPI's support is actually currently available in [committee](https://github.com/interagent/committee/pull/101).
Brandur is working on improving it, but it's there.
