### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by joshwlewis** [heroku/plexy#3]
Should support some type of middleware where operations can modify the log object, or react to it.

- Should support middleware
- GenServer for storing current log context

**Comment by mathias** [comment]
* Support for params blacklist (Retractor?) -- required?
* Support for Rollbar through https://github.com/elixir-addicts/rollbax

**Comment by Adovenmuehle** [comment]
From here: https://github.com/interagent/pliny/wiki/Logging
I think we'd want to have the ability to have global and local context. Don't necessarily think we need the `RequestStore` functionality for now.

We should have support for elapsed time which we should be able to basically take from https://github.com/elixir-lang/plug/blob/master/lib/plug/logger.ex#L31

**Comment by joshwlewis** [comment]
Fixed by #10.
