### ISSUE TITLE
metrics reporter logger middleware

### ISSUE THREAD

**Issue by mathias** [heroku/plexy#4]
The Metrics module in API are convenience functions that API provides that we might want to include as helper functions -- `count`, `sample`, `measure`, `event` etc

**Comment by mathias** [comment]
And here's Pliny's implementation of helper functions: https://github.com/interagent/pliny/blob/1b5caf7ebcd9cc3d8d3161cfdb75222faa030224/lib/pliny/metrics.rb

**Comment by kennyp** [comment]
Closed by #10
